<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Perfil del Estudiante</strong></center>
        </div>
    </div>
<div class="mt-3 mb-2">
<select name="grupos" id="grupos" class="form-select">
    <?= $this->grupos?>
</select>
</div>


    <div class="row">
        <div class="col">
            <table id="table" class="tablaDatosEstudiante">
                <thead>
                    <tr>
                        <th>ID Alumno</th>
                        <th>Nombre Completo</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

</div>