<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Pruebas Físico-Motrices del Estudiante</strong></center>
        </div>
    </div>
    <div class="mt-3 mb-2">
        <select name="pruebaGrupos" id="pruebaGrupos" class="form-select">
            <?= $this->grupos ?>
        </select>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaPruebas">
                <thead>
                    <tr>
                        <th>Estudiante</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- MODAL: AGREGAR Prueba Físico-Motriz del Estudiante -->

<div class="modal fade" id="modalAgregarPrueba" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Pruebas Físico-Motrices
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarPrueba">

                        <!-- IDs -->
                        <input type="hidden" id="idEstudiante" name="idEstudiante">
                        <input type="hidden" id="idGrupo" name="idGrupo">

                        <!-- Foto Estudiante -->
                        <img src="" id="fotoEstudiante" class="rounded mx-auto d-block mb-2"
                            style="width:150px; height:auto">
                        <span class="h3 text-center text-capitalize mb-2" id="nombreCompleto"></span>

                        <div class="mb-2 col-3">
                            <label for="fecha" class="form-label">Fecha de la Prueba</label>
                            <input type="date" class="form-control" id="fecha" name="fecha">
                        </div>

                        <div class="mb-2 col-3">
                            <label for="prueba" class="form-label">Tipo de Prueba</label>
                            <select name="prueba" id="prueba" class="form-select">
                                <option value="0">Seleccione tipo de prueba</option>
                                <option value="Resistencia">Resistencia</option>
                                <option value="Fuerza">Fuerza</option>
                                <option value="Velocidad">Velocidad</option>
                                <option value="Salto">Salto</option>
                                <option value="Lanzamiento">Lanzamiento</option>
                            </select>
                        </div>

                        <div class="mb-2 col-3">
                            <label for="resultado" class="form-label">Resultado</label>
                            <input type="number" class="form-control" id="resultado" name="resultado">
                        </div>

                        <div class="mb-2 col-3">
                            <label for="medida" class="form-label">Unidad de Medida</label>
                            <input type="text" class="form-control" id="medida" name="medida" disabled>
                        </div>

                        <div class="mb-2 col-12">
                            <label for="observacion" class="form-label">Observaciones</label>
                            <textarea class="form-control" id="observacion" name="observacion"></textarea>
                        </div>

                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button type="submit" class="btn btn-primary">Agregar Prueba Físico-Motriz</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>