<section class="profile">
  <!-- TITUTULO -->
  <div class="pagetitle ml-4 mr-4">
    <p class="h2 d-flex justify-content-center mb-2">Datos Personales</p>
    <!-- Pestañas del título -->
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item h4"><a href="index.html">Inicio</a></li>
        <li class="breadcrumb-item h4 active">Datos Personales</li>
      </ol>
    </nav>
  </div><!-- Final del Título -->


  <!-- PERFIL -->
  <div class="row ml-4 mr-4 d-flex justify-content-between">
    <!-- Seccion izquierda -->
    <div class="col-xl-3 card border border-primary-subtle rounded">

    <div class="h5 text-danger text-center mt-3"> ATENCIÓN<br>Sobrepeso</div>
      <div class="card-body profile-card d-flex flex-column align-items-center">
        <?= $this->nombres ?>
      </div>
      <!-- Final de la sección izquierda -->
    </div>

    <!-- Seccion derecha -->
    <div class="col-xl ml-4 card border border-primary-subtle rounded">
      <div class="card-body profile-card d-flex flex-column">
        <ul class="nav nav-tabs nav-tabs-bordered d-flex justify-content-center">

          <li class="nav-item">
            <button class="nav-link active fs-2" data-bs-toggle="tab" data-bs-target="#datosGenerales">Datos
              Generales</button>
          </li>

          <li class="nav-item">
            <button class="nav-link fs-2" data-bs-toggle="tab" data-bs-target="#datosSalud">Datos de Salud</button>
          </li>

        </ul>
        <div class="tab-content pt-1">
          <div class="tab-pane fade show active justify-content-center align-items-center align-content-center"
            id="datosGenerales">
            <span class="card-title fs-3">Detalles del estudiante</span>
            <?= $this->generales ?>
          </div>

          <div
            class="tab-pane fade show active profile-overview justify-content-center align-items-center align-content-center"
            id="datosSalud">
            <span class="card-title fs-3">Detalles de salud</span>
            <?= $this->desalud ?>
          </div>

        </div>
      </div>




      <!-- Final de la sección derecha -->
    </div>



    <!--Final del PERFIL-->
  </div>

</section>