<section class="section dashboard py-4">
    <div class="container">
        <div class="row justify-content-center">
            <!-- Sección izquierda -->
            <div class="col-md-4 mb-4">
                <img src="<?= PLANTILLA ?>images/logo/cPositivo.png" class="img-fluid mx-auto d-block" alt="Logo">
            </div>

            <!-- Sección derecha -->
            <div class="col-md-8">
                <div class="card border-primary-subtle rounded">
                    <div class="card-body text-center">
                        <h1 class="display-4">Bienvenidos a Salud.Edu, donde la salud de los estudiantes es nuestra misión y su bienestar nuestro mayor logro.</h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-md-12 text-center">
                <p class="fs-4">
                    <span class="h3 bg-body-tertiary fw-bolder border-bottom border-info">¡Con Salud.Edu</span>, tu escuela identificará riesgos más rápido!
                </p>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-md-3 mb-4">
                <div class="card border-primary-subtle rounded">
                    <div class="card-body text-center">
                        <h4 class="mb-2">Estudiantes</h4>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1215</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">registrados</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1352</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">con perfiles de salud activos</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1953</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">asistiendo a eventos</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3 mb-4">
                <div class="card border-primary-subtle rounded">
                    <div class="card-body text-center">
                        <h4 class="mb-2">Obesidad</h4>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1215</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">en riesgo</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1352</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">identificados</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1953</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">con planes de ejercicio</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3 mb-4">
                <div class="card border-primary-subtle rounded">
                    <div class="card-body text-center">
                        <h4 class="mb-2">Escuelas</h4>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1215</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">usando <span class="text-success">Salud.Edu</span></div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1352</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">reportes generados</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1953</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">planes creados</div>
                        </div>
                    </div>
                </div>
            </div >

            <div class="col-md-3 mb-4">
                <div class="card border-primary-subtle rounded">
                    <div class="card-body text-center">
                        <h4 class="mb-2">API</h4>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1215</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">llamadas</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1352</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">consultas</div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4 fs-5 fw-bold">1953</div>
                            <div class="col fs-5 fw-bold border-bottom border-info text-center">integraciones</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-md-12 text-center">
                <p class="fs-4">
                    <span class="h3 bg-body-tertiary fw-bolder border-bottom border-info">¡Con Salud.Edu</span>, tu escuela identificará riesgos más rápido!
                </p>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-md-12 text-center">
                <button class="btn btn-primary" type="button">Ver más</button>
            </div>
        </div>
    </div>
</section>

<section class="section dashboard m-4">
    <div class="row m-4 d-flex justify-content-between">
        <!-- Sección izquierda -->
        <div class="col-4">
            <img src="<?= PLANTILLA ?>images/logo/cPositivo.png" style="width:500px; height:auto"
                class="mx-auto d-block">

            <!-- Final Sección izquieda -->
        </div>

        <!-- Seccion derecha -->
        <div class="col-xl ml-4 card border border-primary border-left-0 rounded d-flex justify-content-center">
            <span class="h1 text-center">Bienvenidos a Salud.Edu, donde la salud de los estudiantes es nuestra misión y
                su bienestar nuestro mayor logro.</span>


            <!-- Final Sección derecha -->
        </div>
    </div>

    <div class="row m-2 d-flex justify-content-between text-center">
    <div class="row m-3 d-flex justify-content-between text-center">
            <p class="fs-4">
                <span class="h3 bg-body-tertiary fw-bolder border-bottom border-info">¡Con Salud.Edu</span>, tu escuela identificará riesgos más
                rápido!
            </p>
        </div>    

        <div class="col-3 mr-1 card border border-primary-subtle rounded d-flex justify-content-center text-center">
            <div class="fs-4 text-bold text-black mt-2 mb-2">Estudiantes</div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1215</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">registrados</div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1352</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">con perfiles de salud activos
                </div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1953</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">asistiendo a eventos</div>
            </div>
        </div>

        <div class="col-3 mr-1 card border border-primary-subtle rounded d-flex justify-content-center text-center">
            <div class="fs-4 text-bold text-black mb-2">Obesidad</div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1215</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">en riesgo</div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1352</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">identificados</div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1953</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">con planes de ejercicio</div>
            </div>
        </div>



        <div class="col ml-1 card border border-primary-subtle rounded d-flex justify-content-center">
            <div class="fs-4 text-bold text-black mb-2">Escuelas</div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1215</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">usando <span
                        class="text-success">Salud.Edu</span></div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1352</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">reportes generados</div>
            </div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1953</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">planes creados</div>
            </div>
        </div>

        <div class="col ml-1 card border border-primary-subtle rounded d-flex justify-content-center">
            <div class="fs-4 text-bold text-black mb-2">API</div>
            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">1,215,252</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">registros enviados al MINSA</span>
                </div>
            </div>

            <div class="row mt-1 mb-2 pr-3">
                <div class="col-4 fs-5  text-bold">3,654,335</div>
                <div class="col fs-5 fw-bolder border-bottom border-info text-center">datos de salud exportados</div>
            </div>
        </div>


    </div>

    <div class="row m-3 d-flex justify-content-between text-center">
        <p class="fs-4">
            <span class="h3 bg-body-tertiary fw-bolder border-bottom border-info">¿Sabías que...</span> en Salud.Edu
            puedes visualizar el progreso de tu salud con gráficos interactivos?
        </p>
    </div>

    <div class="row m-1 d-flex justify-content-between align-items-center">

        <!-- Left side columns -->
        <div class="col-lg-8">
            <div class="row">
                <!-- Reports -->
                <div class="col-12">
                    <div class="card">

                        <div class="filter">
                            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                <li class="dropdown-header text-start">
                                    <h6>Filter</h6>
                                </li>

                                <li><a class="dropdown-item" href="#">Today</a></li>
                                <li><a class="dropdown-item" href="#">This Month</a></li>
                                <li><a class="dropdown-item" href="#">This Year</a></li>
                            </ul>
                        </div>

                        <div class="card-body">
                            <h5 class="card-title">Reportes de <span>Hoy</span></h5>

                            <!-- Line Chart -->
                            <div id="reportsChart"></div>

                            <script>
                                document.addEventListener("DOMContentLoaded", () => {
                                    new ApexCharts(document.querySelector("#reportsChart"), {
                                        series: [{
                                            name: 'Nuevos estudiantes',
                                            data: [31, 40, 28, 51, 42, 82, 56],
                                        }, {
                                            name: 'Planes de ejercicio',
                                            data: [11, 32, 45, 32, 34, 52, 41]
                                        }, {
                                            name: 'Escuelas que usan Salud.Edu',
                                            data: [15, 11, 32, 18, 9, 24, 11]
                                        }],
                                        chart: {
                                            height: 350,
                                            type: 'area',
                                            toolbar: {
                                                show: false
                                            },
                                        },
                                        markers: {
                                            size: 4
                                        },
                                        colors: ['#4154f1', '#2eca6a', '#ff771d'],
                                        fill: {
                                            type: "gradient",
                                            gradient: {
                                                shadeIntensity: 1,
                                                opacityFrom: 0.3,
                                                opacityTo: 0.4,
                                                stops: [0, 90, 100]
                                            }
                                        },
                                        dataLabels: {
                                            enabled: false
                                        },
                                        stroke: {
                                            curve: 'smooth',
                                            width: 2
                                        },
                                        xaxis: {
                                            type: 'datetime',
                                            categories: ["2018-09-19T00:00:00.000Z", "2018-09-19T01:30:00.000Z", "2018-09-19T02:30:00.000Z", "2018-09-19T03:30:00.000Z", "2018-09-19T04:30:00.000Z", "2018-09-19T05:30:00.000Z", "2018-09-19T06:30:00.000Z"]
                                        },
                                        tooltip: {
                                            x: {
                                                format: 'dd/MM/yy HH:mm'
                                            },
                                        }
                                    }).render();
                                });
                            </script>
                            <!-- End Line Chart -->

                        </div>

                    </div>
                </div><!-- End Reports -->

            </div>
        </div><!-- End Left side columns -->


        <!-- Right side columns -->
        <div class="col-lg-4">

            <!-- Recent Activity -->
            <div class="card text-center border-0">
                <div class="card-body">
                    <p class="fs-4 pt-8 pb-8">Monitorea fácilmente tu peso, IMC y otros indicadores clave a lo largo del
                        tiempo,
                        ayudándote a seguir tus mejoras y mantener un estilo de vida saludable. ¡Todo en un solo lugar y
                        accesible cuando lo necesites!</p>

                </div>
            </div><!-- End Recent Activity -->

        </div><!-- End Right side columns -->

        <div class="row m-3 d-flex justify-content-between text-center">
            <p class="fs-4">
                <span class="h3 bg-body-tertiary fw-bolder border-bottom border-info">¿Te interesa</span> practicar algún deporte o quieres saber qué tan cerca tienes un local?
            </p>
        </div>

    </div>
</section>

</main>