<div class="container-fluid">
    <div class="row mt-4">
        <div class="col">
            <div style="height:500px;width:100%" id="map"></div>
        </div>
    </div>
</div>


<script>
    var map = L.map('map').setView([13.483288219415183, -86.5832157754854], 13);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy;gymbroapp'
    }).addTo(map);


    let ubicaciones=JSON.parse('<?= $this->datos ?>');
    console.log(ubicaciones);

    for(i=0;i<ubicaciones.length;i++){
        L.marker([ubicaciones[i]['latitud'], ubicaciones[i]['longitud']]).addTo(map)
        .bindPopup('<div id="card" class="card shadow mb-4"><div class="card-header py-3"><h6 class="m-0 font-weight-bold text-primary">Gimnasio '+[ubicaciones[i]['nombre']]+'</h6></div><div class="card-body">Dirección: '+[ubicaciones[i]['direccion']]+'<br> <hr> Latitud: '+[ubicaciones[i]['latitud']]+' <br> <hr> Longitud: '+[ubicaciones[i]['longitud']]+'  <br><hr>Hora Abre: '+[ubicaciones[i]['hora_apertura']]+' <br> <hr> Hora cierra: '+[ubicaciones[i]['hora_cierre']]+'  <br><hr> <img class="rounded mx-auto d-block" style="height:80px"; src="<?=PLANTILLA?>images/'+[ubicaciones[i]['imagen']]+'"> <br>  </div></div>');
        
    }


</script>