<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Docentes</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarDocente" data-bs-toggle="modal" class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Docente</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaDocentes">
                <thead>
                    <tr>
                        <th>ID Docente</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th>Teléfono</th>
                        <th>Acciones</th>
                    </tr>
                </thead> 
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

</div>


<!-- Modal agregar Docente -->

    <div class="modal fade" id="modalAgregarDocente" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Docente</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarDocente" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="id_escuela" class="form-label">Escuela en la que labora</label>
                            <select class="form-select" name="id_escuela" id="id_escuela"> 
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombreDocente" class="form-label">Nombre</label>
                            <input type="text" class="form-control" id="nombreDocente" name="nombreDocente">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="apellidoDocente" class="form-label">Apellido</label>
                            <input type="text" class="form-control" id="apellidoDocente" name="apellidoDocente">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="emailDocente" class="form-label">Email</label>
                            <input type="email" class="form-control" id="emailDocente" name="emailDocente">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="telefonoDocente" class="form-label">Teléfono</label>
                            <input type="tel" class="form-control" id="telefonoDocente" name="telefonoDocente">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="usuarioDocente" class="form-label">Usuario</label>
                            <input type="text" class="form-control" id="usuarioDocente" name="usuarioDocente">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="claveDocente" class="form-label">Clave</label>
                            <input type="password" class="form-control" id="claveDocente" name="claveDocente">
                        </div>

                        
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>


    <!-- Modal Actualizar Docente -->
<!-- Modal Actualizar Docente -->

<div class="modal fade" id="modalEditarDocente" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Docente</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarDocente" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idDocenteUp" class="form-label">ID Docente</label>
                            <input type="text" id="idDocenteUp" name="idDocenteUp" class="form-control" disabled>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="escuelaDocenteUp" class="form-label">Escuela en la que labora</label>
                            <select class="form-select" id="escuelaDocenteUp" name="escuelaDocenteUp"> 
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombreDocenteUp" class="form-label">Nombre</label>
                            <input type="text" class="form-control" id="nombreDocenteUp" name="nombreDocenteUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="apellidoDocenteUp" class="form-label">Apellido</label>
                            <input type="text" class="form-control" id="apellidoDocenteUp" name="apellidoDocenteUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="emailDocenteUp" class="form-label">Email</label>
                            <input type="email" class="form-control" id="emailDocenteUp" name="emailDocenteUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="telefonoDocenteUp" class="form-label">Teléfono</label>
                            <input type="tel" class="form-control" id="telefonoDocenteUp" name="telefonoDocenteUp">
                        </div>
                        
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>