<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Municipios</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarMunicipio" data-bs-toggle="modal"
                class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Municipios</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaMunicipios">
                <thead>
                    <tr>
                        <th>Departamento</th>
                        <th>ID Municipio</th>
                        <th>Nombre Municipio</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>
</div>

<!--Modal para AGREGAR Municipios-->
<div class="modal fade" id="modalAgregarMunicipio" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Municipio</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarMunicipio" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="dptoId" class="form-label">Seleccione el Departamento</label>
                            <select name="dptoId" id="dptoId" class="form-select">
                                <?= $this->departamento ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="municipio" class="form-label">Nombre del municipio</label>
                            <input type="text" class="form-control" id="municipio" name="municipio">
                        </div>

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar municipio</button>
            </div>

            </form>
        </div>
    </div>
</div>

<!-- Modal para EDITAR MUNICIPIOS -->
<div class="modal fade" id="modalEditarMunicipio" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Municipio</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarMunicipio" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="muniIdUp" class="form-label">ID Municipio</label>
                            <input type="text" class="form-control" id="muniIdUp" name="muniIdUp" disabled>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="municipioUp" class="form-label">Nombre del Municipio</label>
                            <input type="text" class="form-control" id="municipioUp" name="municipioUp">
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>