<div class="container">
    <div class="row mt-3">
        <div class="col">
        <center><strong>Registro y Listado de Maestros</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarMaestro" data-bs-toggle="modal" class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Maestro</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table">
                <thead>
                    <tr>
                        <th>ID Maestro</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th>Teléfono</th>
                        <th>Perfil</th>
                        <th>Acciones</th>
                    </tr>
                </thead> 
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

</div>


<!-- Modal agregar Maestro -->

    <div class="modal fade" id="modalAgregarMaestro" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Maestro</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarMaestro" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Escuela en la que labora</label>
                            <select class="form-select" name="" id="id"> 
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombreMaestro" class="form-label"></label>
                            <input type="" class="form-control" id="nombreMaestro" name="nombreMaestro">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="apellidoMaestro" class="form-label"></label>
                            <input type="" class="form-control" id="apellidoMaestro" name="apellidoMaestro">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="emailMaestro" class="form-label"></label>
                            <input type="" class="form-control" id="emailMaestro" name="emailMaestro">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="telefonoMaestro" class="form-label"></label>
                            <input type="" class="form-control" id="telefonoMaestro" name="telefonoMaestro">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="perfilMaestro" class="form-label"></label>
                            <input type="" class="form-control" id="perfilMaestro" name="perfilMaestro">
                        </div>


                        
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>


    <!-- Modal Actualizar Maestro -->

    <div class="modal fade" id="modalActualizarMaestro" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Actualizar Datos de Maestro</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarMaestros" enctype="multipart/form-data">
                        
                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">ID Maestro</label>
                            <input type="text" class="form-control" id="idUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Escuela Labora</label>
                            <select class="form-select" name="" id="id"> 
                                
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Nombres Maestro</label>
                            <input type="text" class="form-control" id="nombre" >
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Apellidos Maestro</label>
                            <input type="text" class="form-control" id="apellido">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Correo Electronico</label>
                            <input type="email" class="form-control" id="correo">
                        </div>


                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono</label>
                            <input type="tel" class="form-control" id="telefono">
                        </div>

                        

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Perfil</label>
                            <input type="text" class="form-control" id="perfil">
                        </div>

                        


                       
                       
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>