<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Materias</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button class="btn btn-primary float-right" data-bs-target="#modalAgregarMateria" data-bs-toggle="modal">
                <i class="fas fa-solid fa-plus"></i> Agregar Materia
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaMateria">
                <thead>
                    <tr>
                        <th>ID Materia</th>
                        <th>Grupo</th>
                        <th>Materia</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal Agregar Materia -->
    <div class="modal fade" id="modalAgregarMateria" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Materia</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="formAgregarMateria" method="post" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="id_grupo" class="form-label">Grupo</label>
                            <select class="form-select" name="id_grupo" id="id_grupo">
                                <?= $this->grupos ?>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="nombre_materia" class="form-label">Materia</label>
                            <input type="text" class="form-control" id="nombre_materia" name="nombre_materia">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary">Guardar Materia</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Editar Materia -->
<div class="modal fade" id="modalEditarMateria" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Materia</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formEditarMateria" method="post" enctype="multipart/form-data">

                    <div class="mb-3">
                        <label for="id_materia" class="form-label">ID Materia</label>
                        <input type="text" id="id_materia" name="id_materia" class="form-control" disabled>
                    </div>

                    <div class="mb-3">
                        <label for="grupoUp" class="form-label">Grupo</label>
                        <select class="form-select" name="grupoUp" id="grupoUp">
                            <?= $this->grupos ?>
                        </select>

                    </div>
                    <div class="mb-3">
                        <label for="materiaUp" class="form-label">Materia</label>
                        <input type="text" class="form-control" id="materiaUp" name="materiaUp">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>