<div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
    <div class="d-flex flex-column justify-content-between">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-10">
                <div class="card card-default mb-0">
                    <div class="card-header pb-0">
                        <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                            <a class="w-auto pl-0" href="/index.html">
                                <img src="images/logo.png" alt="Mono">
                                <span class="brand-name text-dark">MONO</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body px-5 pb-5 pt-0">
                        <h4 class="text-dark mb-6 text-center">Sign in for free</h4>
                        <form method="post">
                            <?php
                            if (isset($this->mensaje))
                                echo $this->mensaje;
                            ?>
                            <input type="hidden" name="validar" value='1'>
                            <div class="row">
                                <div class="form-group col-md-12 mb-4">
                                    <input type="text" class="form-control input-lg" placeholder="Ingrese su usuario"
                                        name="user">
                                </div>
                                <div class="form-group col-md-12 ">
                                    <input type="password" class="form-control input-lg" name="clave"
                                        placeholder="Ingrese su contraseña">
                                </div>
                                <div class="col-md-12">

                                    <div class="d-flex justify-content-between mb-3">

                                        <a class="text-color" href="#"> ¿Ha olvidado su contraseña? </a>

                                    </div>

                                    <button type="submit" class="btn btn-primary btn-pill mb-4">Sign In</button>

                                    <p>Don't have an account yet ?
                                        <a class="text-blue" href="sign-up.html">Sign Up</a>
                                    </p>
                                </div>
                            </div>
                        </formd=>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>