<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12 d-flex justify-content-center align-items-center">
            <div class="card" style="width:80% !important;">
                <div class="card-header mb-3">
                    Registro de Estudiantes
                </div>
                <div class="row m-auto">
                    <form class="row" method="post" id="formAgregarAlumno" enctype="multipart/form-data">
                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Escuela Asiste</label>
                            <select class="form-select" name="id" id="id">
                                <?= $this->escuelas ?>
                            </select>
                        </div>


                        <div class="mb-3 col-lg-3">
                            <label for="" class="form-label">Primer Nombre</label>
                            <input type="text" class="form-control" name="pNombre" id="pNombre">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="" class="form-label">Segundo Nombre</label>
                            <input type="text" class="form-control" name="sNombre" id="sNombre">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="" class="form-label">Primer Apellido</label>
                            <input type="text" class="form-control" name="pApellido" id="pApellido">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="" class="form-label">Segundo Apellido</label>
                            <input type="text" class="form-control" name="sApellido" id="sApellido">
                        </div>

                        <div class="mb-3 col-lg-4">
                            <label for="" class="form-label">Fecha de Nacimiento</label>
                            <input type="date" class="form-control" name="fecha" id="fecha">
                        </div>

                        <div class="mb-3 col-lg-4">
                            <label for="" class="form-label">Edad</label>
                            <input type="text" class="form-control" name="edad" id="edad">
                        </div>


                        <div class="mb-3 col-lg-4">
                            <label for="" class="form-label">Sexo</label>
                            <select name="" class="form-select" name="sexo" id="sexo">
                                <option value="0">SELECCIONE UNA OPCIÓN</option>
                                <option value="masculino">Masculino</option>
                                <option value="femenino">Femenino</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono Alumno</label>
                            <input type="tel" class="form-control" name="telefonoAlumno" id="telefonoAlumno">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Correo Electronico</label>
                            <input type="email" class="form-control" name="correo" id="correo">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Dirección Reside</label>
                            <textarea class="form-control" name="direccion" id="direccion"></textarea>
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Nombre Tutor</label>
                            <input type="text" class="form-control" name="nombreTutor" id="nombreTutor">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono Tutor</label>
                            <input type="tel" class="form-control" name="telefonoTutor" id="telefonoTutor">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Foto Estudiante</label>
                            <input type="file" class="form-control" name="imagenEstudiante" id="imagenEstudiante">
                        </div>

                </div>

                <div class="card-footer text-body-secondary">
                    <div class="row justify-content-end">
                        <div class="col-4">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i>
                                Guardar
                                cambios</button>
                        </div>
                    </div>
                </div>

                </form>



            </div>

        </div>

    </div>
</div>