<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Estudiantes</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarEstudiante" data-bs-toggle="modal"
                class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Estudiante</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaEstudiantes">
                <thead>
                    <tr>
                        <th>Escuela</th>
                        <th>ID</th>
                        <th>Nombre Completo</th>
                        <th>Edad</th>
                        <th>F. Nacimiento</th>
                        <th>Sexo</th>
                        <th>Dirección</th>
                        <th>Teléfono</th>
                        <th>Email</th>
                        <th>Tutor</th>
                        <th>Tel. Tutor</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

<!-- Modal agregar Estudiante -->

<div class="modal fade" id="modalAgregarEstudiante" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Estudiante</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarEstudiante" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idEscuela" class="form-label">Escuela</label>
                            <select class="form-select" name="idEscuela" id="idEscuela">
                                <?= $this->escuelas ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="pNombre" class="form-label">Primer Nombre</label>
                            <input type="text" class="form-control" id="pNombre" name="pNombre">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="sNombre" class="form-label">Segundo Nombre</label>
                            <input type="text" class="form-control" id="sNombre" name="sNombre">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="pApellido" class="form-label">Primer Apellido</label>
                            <input type="text" class="form-control" id="pApellido" name="pApellido">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="sApellido" class="form-label">Segundo Apellido</label>
                            <input type="text" class="form-control" id="sApellido" name="sApellido">
                        </div>

                        <div class="mb-3 col-lg-4">
                            <label for="edad" class="form-label">Edad</label>
                            <input type="number" class="form-control" id="edad" name="edad">
                        </div>

                        <div class="mb-3 col-lg-4">
                            <label for="nacimiento" class="form-label">Fecha Nacimiento</label>
                            <input type="date" class="form-control" id="nacimiento" name="nacimiento">
                        </div>

                        <div class="mb-3 col-lg-4">
                            <label for="sexo" class="form-label">Sexo</label>
                            <select class="form-select" name="sexo" id="sexo">
                                <option value="0">Seleccione sexo del estudiante</option>
                                <option value="Masculino">Masculino</option>
                                <option value="Femenino">Femenino</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="direccion" class="form-label">Dirección</label>
                            <input type="text" class="form-control" id="direccion" name="direccion">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="telefono" class="form-label">Teléfono</label>
                            <input type="tel" class="form-control" id="telefono" name="telefono">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="tutor" class="form-label">Nombre Tutor</label>
                            <input type="text" class="form-control" id="tutor" name="tutor">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="tutorTel" class="form-label">Teléfono Tutor</label>
                            <input type="tel" class="form-control" id="tutorTel" name="tutorTel">
                        </div>

                        <div class="mb-3 col-lg-3">
                            <label for="estado" class="form-label">Estado</label>
                            <select class="form-select" name="estado" id="estado">
                                <option value="Activo">Activo</option>
                                <option value="Inactivo">Inactivo</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="foto" class="form-label">Foto del Estudiante</label>
                            <input type="file" class="form-control" id="foto" name="foto">
                        </div>

                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button type="submit" class="btn btn-primary">Registrar Estudiante</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal editar Estudiante -->

<div class="modal fade" id="modalEditarEstudiante" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Estudiante</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarEstudiante" enctype="multipart/form-data">

                        <input type="hidden" id="idEstudiante" name="idEstudiante">

                        <div class="mb-3 col-lg-12">
                            <label for="idEscuelaUp" class="form-label">Escuela</label>
                            <select class="form-select" name="idEscuelaUp" id="idEscuelaUp">
                                <?= $this->escuelas ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="pNombreUp" class="form-label">Primer Nombre</label>
                            <input type="text" class="form-control" id="pNombreUp" name="pNombreUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="sNombreUp" class="form-label">Segundo Nombre</label>
                            <input type="text" class="form-control" id="sNombreUp" name="sNombreUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="pApellidoUp" class="form-label">Primer Apellido</label>
                            <input type="text" class="form-control" id="pApellidoUp" name="pApellidoUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="sApellidoUp" class="form-label">Segundo Apellido</label>
                            <input type="text" class="form-control" id="sApellidoUp" name="sApellidoUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="edadUp" class="form-label">Edad</label>
                            <input type="number" class="form-control" id="edadUp" name="edadUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nacimientoUp" class="form-label">Fecha Nacimiento</label>
                            <input type="date" class="form-control" id="nacimientoUp" name="nacimientoUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="sexoUp" class="form-label">Sexo</label>
                            <select class="form-select" name="sexoUp" id="sexoUp">
                                <option value="Masculino">Masculino</option>
                                <option value="Femenino">Femenino</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="direccionUp" class="form-label">Dirección</label>
                            <input type="text" class="form-control" id="direccionUp" name="direccionUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="telefonoUp" class="form-label">Teléfono</label>
                            <input type="tel" class="form-control" id="telefonoUp" name="telefonoUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="emailUp" class="form-label">Email</label>
                            <input type="email" class="form-control" id="emailUp" name="emailUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="tutorUp" class="form-label">Nombre Tutor</label>
                            <input type="text" class="form-control" id="tutorUp" name="tutorUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="tutorTelUp" class="form-label">Teléfono Tutor</label>
                            < input type="tel" class="form-control" id="tutorTelUp" name="tutorTelUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="fotoUp" class="form-label">Imagen</label>
                            <input type="file" class="form-control" id="fotoUp" name="fotoUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="estadoUp" class="form-label">Estado</label>
                            <select class="form-select" name="estadoUp" id="estadoUp">
                                <option value="Activo">Activo</option>
                                <option value="Inactivo">Inactivo</option>
                            </select>
                        </div>

                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button type="submit" class="btn btn-primary">Editar Estudiante</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>