<div class="container">
    <div class="row mt-3">
        <div class="col">
        <center><strong>Registro y Listado de Estudiantes </strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarAlumno" data-bs-toggle="modal" class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Alumno</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre Estudiante</th>
                        <th>Fecha Nacimiento</th>
                        <th>Genero</th>
                        <th>Dirección</th>
                        <th>Telefono</th>
                        <th>Email</th>
                        <th>Nombre Tutor</th>
                        <th>Telefono Tutor</th>
                        <th>Escuela</th>
                        


                        <th>Acción</th>
                    </tr>
                </thead> 
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>






</div>


<!-- Modal agregar Maestro -->

    <div class="modal fade" id="modalAgregarAlumno" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Alumno</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarAlumno" enctype="multipart/form-data">
                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Escuela Asiste</label>
                            <select class="form-select" name="" id="id"> 
                                
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Nombres Alumno</label>
                            <input type="text" class="form-control" id="nombre" >
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Apellidos Alumno</label>
                            <input type="text" class="form-control" id="apellido">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Fecha de Nacimiento</label>
                            <input type="date" class="form-control" id="fecha">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Genero</label>
                            <select name="" class="form-select" id="genero">
                                <option value="0">SELECCIONE UNA OPCIÓN</option>
                                <option value="masculino">Masculino</option>
                                <option value="femenino">Femenino</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Dirección Reside</label>
                            <textarea class="form-control" name="" id="direccion"></textarea>
                        </div>



                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Correo Electronico</label>
                            <input type="email" class="form-control" id="correo">
                        </div>


                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono Alumno</label>
                            <input type="tel" class="form-control" id="telefono">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono Tutor</label>
                            <input type="tel" class="form-control" id="telefonoTutor">
                        </div>

                        

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Nombre Tutor</label>
                            <input type="text" class="form-control" id="nombreTutor">
                        </div>

                        


                       
                       
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>


    <!-- Modal Actualizar Maestro -->

    <div class="modal fade" id="modalActualizarMaestro" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Actualizar Datos de Maestro</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarMaestros" enctype="multipart/form-data">
                        
                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">ID Maestro</label>
                            <input type="text" class="form-control" id="idUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Escuela Labora</label>
                            <select class="form-select" name="" id="id"> 
                                
                                <?=$this->escuelas?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Nombres Maestro</label>
                            <input type="text" class="form-control" id="nombre" >
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Apellidos Maestro</label>
                            <input type="text" class="form-control" id="apellido">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Correo Electronico</label>
                            <input type="email" class="form-control" id="correo">
                        </div>


                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Telefono</label>
                            <input type="tel" class="form-control" id="telefono">
                        </div>

                        

                        <div class="mb-3 col-lg-6">
                            <label for="" class="form-label">Perfil</label>
                            <input type="text" class="form-control" id="perfil">
                        </div>

                        


                       
                       
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar Cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>