<?php
define('APP_NOMBRE','GYMBRO');
define('BASE_URL','http://localhost/GymBro/');
define('DEFAULT_CONTROLLER','index');
define('PLANTILLA',BASE_URL.'Views/plantilla/');
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASS','');
define('DB_NAME','GymBro');
define('DB_CHAR','utf8');