<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Listado de Estudiantes Matriculados</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaMatriculados">
                <thead>
                    <tr>
                        <th>Año y Sección</th>
                        <th>Estudiante</th>
                        <th>Eliminar Matrícula</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>
</div>