<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Departamentos</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarDepartamento" data-bs-toggle="modal"
                class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Departamentos</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaDepartamentos">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>
</div>

<!--Modal para AGREGAR Departamentos-->
<div class="modal fade" id="modalAgregarDepartamento" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Departamento</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarDepartamento" enctype="multipart/form-data">
                        <div class="mb-3 col-lg-12">
                            <label for="nombreDpto" class="form-label">Nombre del departamento</label>
                            <input type="text" class="form-control" id="nombreDpto" name="nombreDpto">
                        </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar Departamento</button>
            </div>
            </form>
        </div>
    </div>
</div>

<!--Modal para EDITAR DEPARTAMENTOS-->
<div class="modal fade" id="modalEditarDepartamento" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Departamento</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarDepartamento" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idDpto" class="form-label">ID Departamento</label>
                            <input type="text" class="form-control" id="idDpto" name="idDpto" disabled>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombreDpto" class="form-label">Nombre del departamento</label>
                            <input type="text" class="form-control" id="nombreDpto" name="nombreDpto">
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>