<div class="container">
    <div class="row mt-3">
        <div class="col">
        <center><strong>Registro y Listado de Departamentos</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarDepartamento" data-bs-toggle="modal" class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Departamentos</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>
</div>


<!--MODAL: Agregar Departamentos-->
    <div class="modal fade" id="modalAgregarDepartamento" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Departamento</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarDepartamento" enctype="multipart/form-data">
                        <div class="mb-3 col-lg-12">
                            <label for="" class="form-label">Nombre del departamento</label>
                            <input type="text" class="form-control" id="nombreDepartamento" name="nombreDepartamento">
                        </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar Departamento</button>
            </div>
            </form>
            </div>
        </div>
    </div>


    <!--MODAL: Actualizar Escuela-->

    <div class="modal fade" id="modalEditarEscuela" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Escuela</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarAlumno" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idEscuela" class="form-label">ID Escuela</label>
                            <input type="text" class="form-control" id="idEscuela" name="idEscuela">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombreEscuelaUp" class="form-label">Nombre de la Escuela</label>
                            <input type="text" class="form-control" id="nombreEscuelaUp" name="nombreEscuelaUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="direccionEscuelaUp" class="form-label">Dirección</label>
                            <textarea name="direccionEscuelaUp" id="direccionEscuelaUp" class="form-control">Introduzca la dirección de la escuela</textarea>
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="telefonoEscuelaUp" class="form-label">Telefono</label>
                            <input type="tel" class="form-control" id="telefonoEscuelaUp" name="telefonoEscuelaUp">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="longitudEscuelaUp" class="form-label">Longitud</label>
                            <input type="tel" class="form-control" id="longitudEscuelaUp" name="longitudEscuelaUp">
                        </div>

                        <div class="mb-3 col-lg-6">
                            <label for="latitudEscuelaUp" class="form-label">Latitud</label>
                            <input type="tel" class="form-control" id="latitudEscuelaUp" name="latitudEscuelaUp">
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
            </form>
            </div>
        </div>
    </div>