<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Ejercicios</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarEjercicio" data-bs-toggle="modal"
                class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Ejercicios</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaEjercicios">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Categoria</th>
                        <th>Duracion</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>
</div>

<!--Modal para AGREGAR Municipios-->
<div class="modal fade" id="modalAgregarEjercicio" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Ejercicios</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarEjercicio" enctype="multipart/form-data">


                        <div class="mb-3 col-lg-12">
                            <label for="ejercicio" class="form-label">Nombre del ejercicio</label>
                            <input type="text" class="form-control" id="ejercicio" name="ejercicio">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="descripcion" class="form-label">Descripcion</label>
                            <input type="text" class="form-control" id="descripcion" name="descripcion">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="categoria" class="form-label">Categoria</label>
                            <input type="text" class="form-control" id="categoria" name="categoria">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="duracion" class="form-label">Duracion</label>
                            <input type="number" class="form-control" id="duracion" name="duracion">
                        </div>

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar municipio</button>
            </div>

            </form>
        </div>
    </div>
</div>

<!-- Modal para EDITAR MUNICIPIOS -->
<div class="modal fade" id="modalEditarEjercicio" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Ejercicio</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarEjercicio" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idEjercicio" class="form-label">ID</label>
                            <input type="text" class="form-control" id="idEjercicio" name="idEjercicio">
                        </div>


                        <div class="mb-3 col-lg-12">
                            <label for="ejercicioUp" class="form-label">Nombre del ejercicio</label>
                            <input type="text" class="form-control" id="ejercicioUp" name="ejercicioUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="descripcionUp" class="form-label">Descripcion</label>
                            <input type="text" class="form-control" id="descripcionUp" name="descripcionUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="categoriaUp" class="form-label">Categoria</label>
                            <input type="text" class="form-control" id="categoriaUp" name="categoriaUp">
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="duracionUp" class="form-label">Duracion</label>
                            <input type="number" class="form-control" id="duracionUp" name="duracionUp">
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>