<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Matricular estudiantes</strong></center>
        </div>
    </div>

    <div class="mt-3 mb-2">
        <label for="matriculaGrupos" class="form-label">Seleccione el grupo en el que se realizará la matrícula</label>
        <select name="matriculaGrupos" id="matriculaGrupos" class="form-select">
            <?= $this->grupos ?>
        </select>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaMatricula">
                <thead>
                    <tr>
                        <th>Estudiante</th>
                        <th>Realizar Matrícula</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col text-center">
            <a href="<?= BASE_URL ?>matriculado"><button class="btn btn-primary">Ver
                    Estudiantes Matriculados</button></a></div>

    </div>
</div>