<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Grupos</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarGrupo" data-bs-toggle="modal" class="btn btn-primary float-right"><i
                    class="fas fa-solid fa-plus"></i> Agregar Grupo</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaGrupos">
                <thead>
                    <tr>
                        <th>ID Grupo</th>
                        <th>Año Lectivo</th>
                        <th>Docente</th>
                        <th>Año Grupo</th>
                        <th>Nombre Grupo</th>
                        <th>Modalidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>
            </table>
        </div>
    </div>

</div>


<!-- Modal agregar Grupo -->

<div class="modal fade" id="modalAgregarGrupo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Grupo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarGrupo" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="lectivo_id" class="form-label">Lectivo</label>
                            <select class="form-select" name="lectivo_id" id="lectivo_id">
                                <?= $this->lectivos ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="docente_id" class="form-label">Docente</label>
                            <select class="form-select" name="docente_id" id="docente_id">
                                <?= $this->docentes ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="axo_grupo" class="form-label">Año Grupo</label>
                            <select type="text" class="form-select" id="axo_grupo" name="axo_grupo">
                                <option value="0">Seleccione grado</option>
                                <option value="primero">Primer grado</option>
                                <option value="segundo">Segundo grado</option>
                                <option value="tercero">Tercer grado</option>
                                <option value="cuarto">Cuarto grado</option>
                                <option value="quinto">Quinto grado</option>
                                <option value="sexto">Sexto grado</option>
                                <option value="séptimo">Séptimo grado</option>
                                <option value="octavo">Octavo grado</option>
                                <option value="noveno">Noveno grado</option>
                                <option value="décimo">Décimo grado</option>
                                <option value="undécimo">Undécimo grado</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="nombre_grupo" class="form-label">Sección</label>
                            <select type="text" class="form-control" id="nombre_grupo" name="nombre_grupo">
                                <option value="0">Seleccione la sección</option>
                                <option value="A">A</option>
                                <option value="B">B</option>
                                <option value="C">C</option>
                                <option value="D">D</option>
                                <option value="E">E</option>
                                <option value="F">F</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="modalidad" class="form-label">Modalidad</label>
                            <select class="form-select" name="modalidad" id="modalidad">
                                <option value="0">Seleccione una modalidad</option>
                                <option value="Matutino">Matutino</option>
                                <option value="Vespertino">Vespertino</option>
                                <option value="Nocturno">Nocturno</option>
                                <option value="Sabatino">Sabatino</option>
                                <option value="Dominical">Dominical</option>
                            </select>
                        </div>


                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar
                    Cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Actualizar Grupo -->
<div class="modal fade" id="modalEditarGrupo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Grupo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarGrupo" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idGrupo" class="form-label">ID Grupo</label>
                            <input type="text" id="idGrupo" name="idGrupo" class="form-control" disabled>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="idAxo" class="form-label">Lectivo</label>
                            <select class="form-select" id="idAxo" name="idAxo">
                                <?= $this->lectivos ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="idDocenteUp" class="form-label">Docente</label>
                            <select class="form-select" id="idDocenteUp" name="idDocenteUp">
                                <?= $this->docentes ?>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="gradoGrupo" class="form-label">Año Grupo</label>
                            <select type="text" class="form-select" id="gradoGrupo" name="gradoGrupo">
                                <option value="0">Seleccione grado</option>
                                <option value="primero">Primer grado</option>
                                <option value="segundo">Segundo grado</option>
                                <option value="tercero">Tercer grado</option>
                                <option value="cuarto">Cuarto grado</option>
                                <option value="quinto">Quinto grado</option>
                                <option value="sexto">Sexto grado</option>
                                <option value="séptimo">Séptimo grado</option>
                                <option value="octavo">Octavo grado</option>
                                <option value="noveno">Noveno grado</option>
                                <option value="décimo">Décimo grado</option>
                                <option value="undécimo">Undécimo grado</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="seccionGrado" class="form-label">Nombre Grupo</label>
                            <select type="text" class="form-control" id="seccionGrado" name="seccionGrado">
                                <option value="0">Seleccione la sección</option>
                                <option value="A">A</option>
                                <option value="B">B</option>
                                <option value="C">C</option>
                                <option value="D">D</option>
                                <option value="E">E</option>
                                <option value="F">F</option>
                            </select>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="modalidadUp" class="form-label">Modalidad</label>
                            <select class="form-select" name="modalidadUp" id="modalidadUp">
                                <option value="Matutino">Matutino</option>
                                <option value="Vespertino">Vespertino</option>
                                <option value="Nocturno">Nocturno</option>
                                <option value="Sabatino">Sabatino</option>
                                <option value="Dominical">Dominical</option>
                            </select>
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar
                    Cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>