<div class="container">
    <div class="row mt-3">
        <div class="col">
            <center><strong>Registro y Listado de Lectivo</strong></center>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button data-bs-target="#modalAgregarLectivo" data-bs-toggle="modal"
                class="btn btn-primary float-right"><i class="fas fa-solid fa-plus"></i> Agregar Año Lectivo</button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="table" class="tablaLectivo">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Año</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?= $this->tabla ?>
                </tbody>

            </table>
        </div>
    </div>
</div>

<!--Modal para AGREGAR Año Lectivo-->
<div class="modal fade" id="modalAgregarLectivo" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Año Lectivo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formAgregarLectivo" enctype="multipart/form-data">
                        <div class="mb-3 col-lg-12">
                            <label for="lectivo" class="form-label">Año Lectivo</label>
                            <input type="text" class="form-control" id="lectivo" name="lectivo">
                        </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar año lectivo</button>
            </div>
            </form>
        </div>
    </div>
</div>

<!--Modal para EDITAR DEPARTAMENTOS-->
<div class="modal fade" id="modalEditarLectivo" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar año lectivo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form class="row" method="post" id="formEditarLectivo" enctype="multipart/form-data">

                        <div class="mb-3 col-lg-12">
                            <label for="idLectivo" class="form-label"></label>
                            <input type="text" class="form-control" id="idLectivo" name="idLectivo" disabled>
                        </div>

                        <div class="mb-3 col-lg-12">
                            <label for="lectivoUp" class="form-label">Año a actualizar</label>
                            <input type="text" class="form-control" id="axo" name="axo">
                        </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
            </form>
        </div>
    </div>
</div>